# Generated by Django 4.2 on 2025-01-15 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('picture', models.URLField(max_length=500)),
            ],
        ),
    ]
