# Generated by Django 4.2 on 2025-01-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
