# Generated by Django 4.2 on 2025-01-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openshop_app", "0003_rename_is_delete_product_is_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_deleted",
            new_name="is_delete",
        ),
    ]
